sudo: false
language: python
env:
  global:
    - OOMMFTCL=$HOME/miniconda/opt/oommf.tcl
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
install:
  # Install conda and add it to PATH
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r

  # Apply some conda settings, update conda and print info about the installation (for debugging)
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a

  # Install numpy and OOMMF
  - conda install -c http://conda.anaconda.org/maxalbert numpy oommf

script:
  - tclsh ${OOMMFTCL} +version
  - make -C src/oommf_scripts data
  - head -n 20 data-generated/dynamic_txyz.txt
  - echo "Test build succeeded."