sudo: false
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
env:
  global:
    - MINICONDA_ROOT=$HOME/miniconda
    - OOMMFTCL=$MINICONDA_ROOT/opt/oommf.tcl
install:
  # Install conda and add it to PATH
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $MINICONDA_ROOT
  - export PATH="$MINICONDA_ROOT/bin:$PATH"
  - hash -r

  # Apply some conda settings, update conda and print info about the installation (for debugging)
  - conda config --set always_yes yes
  - conda update -q conda
  - conda info -a

  # Install numpy and OOMMF
  - conda install -c http://conda.anaconda.org/maxalbert numpy oommf

script:
  - cat $(which oommf)
  - echo $PATH
  #- $MINICONDA_ROOT/bin/tclsh8.5 ${OOMMFTCL} +version
  - tclsh ${OOMMFTCL} +version
  #- tclsh8.5 ${OOMMFTCL} +version
  - make -C src/oommf_scripts data
  - head -n 20 data-generated-oommf/dynamic_txyz.txt
  - echo "Test build succeeded."
