sudo: false
language: python
env:
  global:
    - TCLTKVERSION=8.6
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Install OOMMF
  - conda create -q -n test-environment -c maxalbert python=$TRAVIS_PYTHON_VERSION numpy tk=$TCLTKVERSION oommf
  - source activate test-environment

script:
  - conda list
  - export TCLSH=${CONDA_ROOT}/envs/test-environment/bin/tclsh${TCLTKVERSION}
  - export CONDA_ROOT=$(conda info --root)
  - export OOMMFTCL=${CONDA_ROOT}/envs/test-environment/opt/oommf.tcl
  - ${TCLSH} ${OOMMFTCL} +version
  - make -C src/oommf_scripts data
  - head -n 20 data-generated/dynamic_txyz.txt
  - echo "Test build succeeded."