#!/bin/bash

SRC_DIR=../src/oommf_scripts
OOMMF_SCRIPTS="relaxation_stage.mif dynamic_stage.mif oommf_postprocessing.py"

# Raise error when a variable is not set, and exit as soon as any
# error occurs in the script.
set -o nounset
set -o errexit

# Generate a README.txt file
echo "The data in this directory was automatically generated by the script 'src/oommf_scripts/generate_data_oommf.sh' in this repository and can safely be deleted." > README.txt

# Copy scripts from source directory to this location
for FILENAME in ${OOMMF_SCRIPTS}; do
    cp ${SRC_DIR}/${FILENAME} .;
done

# Run the relaxation stage
tclsh ${OOMMFTCL} boxsi +fg relaxation_stage.mif -exitondone 1
mv relax-*omf relax.omf

# Run the dynamic stage
tclsh ${OOMMFTCL} boxsi +fg dynamic_stage.mif -exitondone 1

# Extract the _txyz file
tclsh ${OOMMFTCL} odtcols < "dynamic.odt" 18 14 15 16 > "dynamic_txyz.txt"

# Extract the spatial magnetisation data to 'mxs.npy', 'mys.npy' and 'mzs.npy'
python oommf_postprocessing.py

# Remove scripts again from this directory
for FILENAME in ${OOMMF_SCRIPTS}; do
    rm ${FILENAME};
done

# Tidy up intermediate files, so that all the remaining files are the
# generated data files we are interested in.
rm -f *.omf
rm -f *.odt
